# Configuration for auto-assign-action
# Docs: https://github.com/kentaro-m/auto-assign-action

# Add reviewers to PRs
addReviewers: true

# Add assignees to PRs
addAssignees: false

# A list of reviewers to be added to PRs (GitHub user or team name)
reviewers:
  - Entropy-rgb
  - HAAHIT

# A list of keywords to be skipped the assigning reviewers
skipKeywords:
  - wip
  - draft
  - skip-review

# A number of reviewers added to the PR
numberOfReviewers: 1

# Ignore draft PRs
ignoreDraft: true

# Minimum number of reviewers required
minimumNumberOfReviewers: 1
