"""Add workspace_activity_log

Revision ID: 4b1d269a3ad8
Revises: 32e55b8f71d4
Create Date: 2026-07-22 19:34:32.909343
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "4b1d269a3ad8"
down_revision: Union[str, None] = "32e55b8f71d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_activity_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=False),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["workspace_id"], ["workspaces.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activity_workspace_date",
        "workspace_activity_log",
        ["workspace_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_activity_workspace_event",
        "workspace_activity_log",
        ["workspace_id", "event_type"],
        unique=False,
    )
    op.alter_column("query_history", "user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("query_history", "user_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index("ix_activity_workspace_event", table_name="workspace_activity_log")
    op.drop_index("ix_activity_workspace_date", table_name="workspace_activity_log")
    op.drop_table("workspace_activity_log")
    # ### end Alembic commands ###
