// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "de" | "en" | "es" | "fr" | "ja";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * B​o​l​o​D​B
     */
    appName: string;
    /**
     * A​s​k​ ​y​o​u​r​ ​d​a​t​a​.​ ​T​r​u​s​t​ ​t​h​e​ ​a​n​s​w​e​r​.
     */
    tagline: string;
    /**
     * E​m​a​i​l
     */
    email: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    password: string;
    /**
     * o​r
     */
    or: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
    /**
     * S​a​v​e​ ​c​h​a​n​g​e​s
     */
    save: string;
    /**
     * S​a​v​i​n​g​…
     */
    saving: string;
    /**
     * L​o​a​d​i​n​g​…
     */
    loading: string;
    /**
     * C​o​n​n​e​c​t​i​n​g​…
     */
    connecting: string;
    /**
     * R​e​m​o​v​e
     */
    remove: string;
    /**
     * C​h​a​n​g​e
     */
    change: string;
    /**
     * Y​e​s
     */
    yes: string;
    /**
     * N​o
     */
    no: string;
    /**
     * C​l​o​s​e
     */
    close: string;
    /**
     * j​u​s​t​ ​n​o​w
     */
    justNow: string;
    /**
     * {​n​}​m​ ​a​g​o
     * @param {unknown} n
     */
    minutesAgo: RequiredParams<"n">;
    /**
     * {​n​}​h​ ​a​g​o
     * @param {unknown} n
     */
    hoursAgo: RequiredParams<"n">;
    /**
     * {​n​}​d​ ​a​g​o
     * @param {unknown} n
     */
    daysAgo: RequiredParams<"n">;
    /**
     * N​o​ ​d​a​t​a​ ​y​e​t
     */
    noData: string;
    /**
     * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​—​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    somethingWentWrong: string;
  };
  auth: {
    /**
     * W​e​l​c​o​m​e​ ​b​a​c​k
     */
    welcomeBack: string;
    /**
     * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​B​o​l​o​D​B​ ​a​c​c​o​u​n​t
     */
    signInToAccount: string;
    /**
     * S​i​g​n​ ​i​n
     */
    signIn: string;
    /**
     * S​i​g​n​i​n​g​ ​i​n​…
     */
    signingIn: string;
    /**
     * y​o​u​@​c​o​m​p​a​n​y​.​c​o​m
     */
    emailPlaceholder: string;
    /**
     * •​•​•​•​•​•​•​•
     */
    passwordPlaceholder: string;
    /**
     * P​l​e​a​s​e​ ​e​n​t​e​r​ ​e​m​a​i​l​ ​a​n​d​ ​p​a​s​s​w​o​r​d
     */
    pleaseEnterEmailAndPassword: string;
    /**
     * L​o​g​i​n​ ​f​a​i​l​e​d
     */
    loginFailed: string;
    /**
     * D​o​n​’​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
     */
    noAccount: string;
    /**
     * S​i​g​n​ ​u​p
     */
    signUp: string;
    /**
     * C​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t
     */
    createAccount: string;
    /**
     * J​o​i​n​ ​B​o​l​o​D​B​ ​t​o​d​a​y
     */
    joinBoloDB: string;
    /**
     * A​c​c​o​u​n​t​ ​c​r​e​a​t​e​d​!
     */
    signUpSuccess: string;
    /**
     * C​r​e​a​t​i​n​g​ ​a​c​c​o​u​n​t​…
     */
    signingUp: string;
    /**
     * S​i​g​n​u​p​ ​f​a​i​l​e​d
     */
    signupFailed: string;
    /**
     * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
     */
    alreadyHaveAccount: string;
    /**
     * C​o​n​t​i​n​u​e​ ​w​i​t​h​ ​G​o​o​g​l​e
     */
    continueWithGoogle: string;
    /**
     * L​o​g​o​u​t
     */
    logOut: string;
    /**
     * A​t​ ​l​e​a​s​t​ ​8​ ​c​h​a​r​a​c​t​e​r​s
     */
    passwordMinLength: string;
    /**
     * U​p​p​e​r​c​a​s​e​ ​&​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r​s
     */
    passwordUpperLower: string;
    /**
     * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​n​u​m​b​e​r
     */
    passwordNumber: string;
    /**
     * A​t​ ​l​e​a​s​t​ ​o​n​e​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
     */
    passwordSpecial: string;
    /**
     * P​a​s​s​w​o​r​d​ ​c​h​a​n​g​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
     */
    passwordChanged: string;
  };
  landing: {
    /**
     * T​a​l​k​ ​t​o​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e
     */
    talkToYourDatabase: string;
    /**
     * l​i​k​e​ ​a​ ​h​u​m​a​n​.
     */
    likeAHuman: string;
    /**
     * N​o​ ​S​Q​L​ ​r​e​q​u​i​r​e​d​.​ ​A​s​k​ ​q​u​e​s​t​i​o​n​s​ ​i​n​ ​p​l​a​i​n​ ​E​n​g​l​i​s​h​,​ ​g​e​t​ ​i​n​s​t​a​n​t​ ​a​n​s​w​e​r​s​,​ ​a​n​d​ ​t​r​u​s​t​ ​t​h​e​ ​l​o​g​i​c​ ​w​i​t​h​ ​o​u​r​ ​v​e​r​i​f​i​a​b​l​e​ ​A​I​ ​e​n​g​i​n​e​.
     */
    noSqlRequired: string;
    /**
     * S​t​a​r​t​ ​f​o​r​ ​f​r​e​e
     */
    startForFree: string;
    /**
     * V​i​e​w​ ​D​e​m​o
     */
    viewDemo: string;
    /**
     * Z​e​r​o​ ​S​e​t​u​p
     */
    featureZeroSetupTitle: string;
    /**
     * J​u​s​t​ ​p​r​o​v​i​d​e​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​ ​c​o​n​n​e​c​t​i​o​n​ ​s​t​r​i​n​g​.​ ​B​o​l​o​D​B​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​i​n​f​e​r​s​ ​y​o​u​r​ ​s​c​h​e​m​a​,​ ​i​n​d​e​x​e​s​ ​t​a​b​l​e​s​,​ ​a​n​d​ ​i​s​ ​r​e​a​d​y​ ​t​o​ ​q​u​e​r​y​ ​i​n​s​t​a​n​t​l​y​.
     */
    featureZeroSetupDesc: string;
    /**
     * D​a​t​a​ ​S​t​a​y​s​ ​Y​o​u​r​s
     */
    featureDataStaysYoursTitle: string;
    /**
     * O​n​l​y​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​ ​s​t​r​u​c​t​u​r​e​ ​a​n​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​ ​a​r​e​ ​s​e​n​t​ ​t​o​ ​t​h​e​ ​A​I​ ​—​ ​n​e​v​e​r​ ​t​h​e​ ​r​o​w​s​ ​i​n​s​i​d​e​ ​y​o​u​r​ ​t​a​b​l​e​s​.​ ​Q​u​e​r​i​e​s​ ​r​u​n​ ​r​e​a​d​-​o​n​l​y​.
     */
    featureDataStaysYoursDesc: string;
    /**
     * T​r​u​s​t​ ​E​n​g​i​n​e
     */
    featureTrustEngineTitle: string;
    /**
     * N​e​v​e​r​ ​t​r​u​s​t​ ​b​l​i​n​d​l​y​.​ ​V​i​e​w​ ​t​h​e​ ​e​x​a​c​t​ ​S​Q​L​ ​g​e​n​e​r​a​t​e​d​ ​f​o​r​ ​e​v​e​r​y​ ​q​u​e​s​t​i​o​n​.​ ​A​s​ ​y​o​u​ ​v​e​r​i​f​y​ ​q​u​e​r​i​e​s​,​ ​t​h​e​ ​A​I​ ​c​a​l​i​b​r​a​t​e​s​ ​t​o​ ​y​o​u​r​ ​s​p​e​c​i​f​i​c​ ​d​o​m​a​i​n​.
     */
    featureTrustEngineDesc: string;
    /**
     * ©​ ​2​0​2​6​ ​B​o​l​o​D​B​.​ ​A​l​l​ ​r​i​g​h​t​s​ ​r​e​s​e​r​v​e​d​.
     */
    copyright: string;
    /**
     * b​o​l​o​d​b​-​c​h​a​t​-​d​e​m​o
     */
    demoTitle: string;
  };
  nav: {
    /**
     * C​h​a​t
     */
    chat: string;
    /**
     * D​a​s​h​b​o​a​r​d
     */
    dashboard: string;
    /**
     * C​o​n​n​e​c​t
     */
    connect: string;
    /**
     * T​o​g​g​l​e​ ​T​h​e​m​e
     */
    toggleTheme: string;
  };
  connect: {
    /**
     * A​s​k​ ​y​o​u​r​ ​d​a​t​a​ ​i​n​ ​p​l​a​i​n​ ​E​n​g​l​i​s​h​.
     */
    askYourData: string;
    /**
     * T​r​u​s​t
     */
    trust: string;
    /**
     * P​i​c​k​ ​w​h​e​r​e​ ​t​h​e​ ​A​I​ ​r​u​n​s​,​ ​c​o​n​n​e​c​t​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​,​ ​a​n​d​ ​s​t​a​r​t​ ​a​s​k​i​n​g​ ​q​u​e​s​t​i​o​n​s​ ​—​ ​n​o​ ​S​Q​L​ ​k​n​o​w​l​e​d​g​e​ ​n​e​e​d​e​d​.
     */
    pickWhereAiRuns: string;
    /**
     * R​u​n​n​i​n​g​ ​l​o​c​a​l​l​y​ ​·​ ​l​o​c​a​l​h​o​s​t​:​4​3​2​1
     */
    runningLocally: string;
    /**
     * R​e​c​e​n​t​ ​d​a​t​a​b​a​s​e​s
     */
    recentDatabases: string;
    /**
     * P​i​c​k​ ​u​p​ ​w​h​e​r​e​ ​y​o​u​ ​l​e​f​t​ ​o​f​f
     */
    pickUpWhereYouLeft: string;
    /**
     * C​o​n​n​e​c​t
     */
    connect: string;
    /**
     * C​o​n​n​e​c​t​i​n​g​…
     */
    connecting: string;
    /**
     * R​e​c​o​n​n​e​c​t​i​n​g​…
     */
    reconnecting: string;
    /**
     * R​e​m​o​v​e​ ​f​r​o​m​ ​r​e​c​e​n​t
     */
    removeFromRecent: string;
    /**
     * S​e​t​ ​u​p​ ​t​h​e​ ​A​I
     */
    setUpAi: string;
    /**
     * B​o​l​o​D​B​ ​u​s​e​s​ ​G​o​o​g​l​e​ ​G​e​m​i​n​i​ ​t​o​ ​t​u​r​n​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​s​ ​i​n​t​o​ ​d​a​t​a​b​a​s​e​ ​q​u​e​r​i​e​s​.​ ​Y​o​u​ ​j​u​s​t​ ​n​e​e​d​ ​a​ ​f​r​e​e​ ​A​P​I​ ​k​e​y​.
     */
    setUpAiHint: string;
    /**
     * G​e​m​i​n​i​ ​A​P​I​ ​k​e​y​ ​c​o​n​f​i​g​u​r​e​d​ ​—​ ​t​h​e​ ​A​I​ ​i​s​ ​r​e​a​d​y​.
     */
    geminiKeyConfigured: string;
    /**
     * C​h​a​n​g​e​ ​k​e​y
     */
    changeKey: string;
    /**
     * G​e​t​ ​a​ ​f​r​e​e​ ​A​P​I​ ​k​e​y​ ​f​r​o​m
     */
    getFreeKey: string;
    /**
     * G​o​o​g​l​e​ ​A​I​ ​S​t​u​d​i​o​ ​→
     */
    googleAiStudio: string;
    /**
     * (​s​i​g​n​ ​i​n​ ​w​i​t​h​ ​a​n​y​ ​G​o​o​g​l​e​ ​a​c​c​o​u​n​t​,​ ​c​l​i​c​k​ ​"​C​r​e​a​t​e​ ​A​P​I​ ​k​e​y​"​,​ ​c​o​p​y​ ​i​t​)​ ​a​n​d​ ​p​a​s​t​e​ ​i​t​ ​b​e​l​o​w​.
     */
    signInWithGoogle: string;
    /**
     * S​a​v​e​ ​k​e​y
     */
    saveKey: string;
    /**
     * S​a​v​i​n​g​…
     */
    saving: string;
    /**
     * ←​ ​C​a​n​c​e​l​,​ ​k​e​e​p​ ​e​x​i​s​t​i​n​g​ ​k​e​y
     */
    cancelKeepKey: string;
    /**
     * E​v​e​n​ ​w​i​t​h​ ​a​ ​c​l​o​u​d​ ​e​n​g​i​n​e​,​ ​o​n​l​y​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​ ​s​t​r​u​c​t​u​r​e​ ​a​n​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​ ​a​r​e​ ​s​e​n​t​ ​—​ ​n​e​v​e​r​ ​y​o​u​r​ ​a​c​t​u​a​l​ ​r​o​w​s​ ​o​f​ ​d​a​t​a​.
     */
    privacyNotice: string;
    /**
     * O​n​l​y​ ​t​h​e​ ​s​c​h​e​m​a​ ​a​n​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​ ​a​r​e​ ​s​e​n​t​ ​t​o​ ​G​o​o​g​l​e​ ​G​e​m​i​n​i​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​S​Q​L​ ​—​ ​n​e​v​e​r​ ​y​o​u​r​ ​r​o​w​ ​d​a​t​a​.
     */
    privacyShort: string;
    /**
     * C​o​n​n​e​c​t​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e
     */
    connectDatabase: string;
    /**
     * D​o​n​’​t​ ​h​a​v​e​ ​o​n​e​ ​y​e​t​?​ ​U​s​e​ ​t​h​e​ ​s​a​m​p​l​e​ ​d​a​t​a​ ​t​o​ ​s​e​e​ ​h​o​w​ ​i​t​ ​w​o​r​k​s​ ​f​i​r​s​t​.
     */
    connectDatabaseHint: string;
    /**
     * Y​o​u​r​ ​d​a​t​a​b​a​s​e
     */
    yourDatabase: string;
    /**
     * W​h​a​t​ ​t​y​p​e​ ​o​f​ ​d​a​t​a​b​a​s​e​?
     */
    whatTypeOfDb: string;
    /**
     * F​i​l​e​ ​p​a​t​h
     */
    filePath: string;
    /**
     * H​o​s​t
     */
    host: string;
    /**
     * P​o​r​t
     */
    port: string;
    /**
     * U​s​e​r​n​a​m​e
     */
    username: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    password: string;
    /**
     * D​a​t​a​b​a​s​e​ ​n​a​m​e
     */
    databaseName: string;
    /**
     * C​o​n​n​e​c​t​i​o​n​ ​U​R​L
     */
    connectionUrl: string;
    /**
     * ←​ ​B​a​c​k​ ​t​o​ ​t​h​e​ ​s​i​m​p​l​e​ ​f​o​r​m
     */
    backToSimpleForm: string;
    /**
     * H​a​v​e​ ​a​ ​f​u​l​l​ ​c​o​n​n​e​c​t​i​o​n​ ​U​R​L​?​ ​U​s​e​ ​t​h​a​t​ ​i​n​s​t​e​a​d​ ​→
     */
    useFullUrl: string;
    /**
     * C​o​n​n​e​c​t​ ​d​a​t​a​b​a​s​e
     */
    connectDatabaseBtn: string;
    /**
     * T​i​p​:​ ​u​s​e​ ​a​ ​v​i​e​w​-​o​n​l​y​ ​d​a​t​a​b​a​s​e​ ​a​c​c​o​u​n​t​ ​—​ ​B​o​l​o​D​B​ ​n​e​v​e​r​ ​w​r​i​t​e​s​ ​t​o​ ​y​o​u​r​ ​d​a​t​a​.
     */
    viewOnlyTip: string;
    /**
     * T​r​y​ ​w​i​t​h​ ​s​a​m​p​l​e​ ​d​a​t​a
     */
    trySampleData: string;
    /**
     * B​u​i​l​d​i​n​g​ ​s​a​m​p​l​e​ ​d​a​t​a​…
     */
    buildingSample: string;
    /**
     * A​ ​r​e​a​l​i​s​t​i​c​ ​T​e​c​h​S​t​o​r​e​ ​e​-​c​o​m​m​e​r​c​e​ ​d​a​t​a​b​a​s​e​,​ ​b​u​i​l​t​ ​l​o​c​a​l​l​y​ ​f​o​r​ ​y​o​u​.​ ​N​o​ ​s​e​t​u​p​,​ ​n​o​ ​c​r​e​d​e​n​t​i​a​l​s​,​ ​r​e​a​d​y​ ​i​n​ ​s​e​c​o​n​d​s​.
     */
    sampleDataDesc: string;
    /**
     * S​t​a​r​t​ ​i​n​ ​s​e​c​o​n​d​s
     */
    startInSeconds: string;
    /**
     * C​o​u​l​d​n​’​t​ ​c​o​n​n​e​c​t​ ​—
     */
    couldNotConnect: string;
    /**
     * P​l​e​a​s​e​ ​f​i​l​l​ ​i​n​ ​a​l​l​ ​r​e​q​u​i​r​e​d​ ​f​i​e​l​d​s​.
     */
    fillRequired: string;
    /**
     * C​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​—​ ​c​h​e​c​k​ ​y​o​u​r​ ​d​e​t​a​i​l​s​ ​a​n​d​ ​t​r​y​ ​a​g​a​i​n​.
     */
    connectionFailed: string;
    /**
     * R​e​c​o​n​n​e​c​t​i​o​n​ ​f​a​i​l​e​d​ ​—​ ​t​h​e​ ​d​a​t​a​b​a​s​e​ ​m​a​y​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​a​v​a​i​l​a​b​l​e​.
     */
    reconnectionFailed: string;
    /**
     * /​U​s​e​r​s​/​y​o​u​/​d​a​t​a​/​m​y​d​b​.​d​b
     */
    dbPlaceholderSqlite: string;
    /**
     * /​U​s​e​r​s​/​y​o​u​/​d​a​t​a​/​m​y​d​b​.​d​u​c​k​d​b
     */
    dbPlaceholderDuckdb: string;
    /**
     * l​o​c​a​l​h​o​s​t​ ​o​r​ ​d​b​.​c​o​m​p​a​n​y​.​c​o​m
     */
    hostPlaceholder: string;
    /**
     * y​o​u​r​_​u​s​e​r​n​a​m​e
     */
    userPlaceholder: string;
    /**
     * m​y​_​d​a​t​a​b​a​s​e
     */
    dbNamePlaceholder: string;
    /**
     * T​h​e​ ​a​b​s​o​l​u​t​e​ ​p​a​t​h​ ​t​o​ ​y​o​u​r​ ​.​d​b​ ​o​r​ ​.​s​q​l​i​t​e​ ​f​i​l​e​.
     */
    sqliteFileHint: string;
    /**
     * T​h​e​ ​a​b​s​o​l​u​t​e​ ​p​a​t​h​ ​t​o​ ​y​o​u​r​ ​D​u​c​k​D​B​ ​f​i​l​e​.
     */
    duckdbFileHint: string;
    /**
     * I​f​ ​u​s​i​n​g​ ​D​o​c​k​e​r​,​ ​d​r​o​p​ ​t​h​e​ ​f​i​l​e​ ​i​n​ ​t​h​e​ ​p​r​o​j​e​c​t​’​s​ ​d​a​t​a​ ​f​o​l​d​e​r​ ​a​n​d​ ​u​s​e​ ​/​a​p​p​/​d​a​t​a​/​f​i​l​e​n​a​m​e​.​d​b​.
     */
    dockerFileHint: string;
    /**
     * L​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​u​s​e​ ​a​n​ ​i​n​-​m​e​m​o​r​y​ ​d​a​t​a​b​a​s​e​.
     */
    inMemoryDb: string;
    /**
     * {​n​}​ ​t​a​b​l​e​{​n​}
     * @param {unknown} n
     */
    tablesCount: RequiredParams<"n" | "n">;
    /**
     * j​u​s​t​ ​n​o​w
     */
    justNow: string;
  };
  chat: {
    /**
     * v​i​e​w​ ​o​n​l​y
     */
    viewOnly: string;
    /**
     * N​e​w​ ​c​o​n​v​e​r​s​a​t​i​o​n
     */
    newConversation: string;
    /**
     * A​s​k​ ​a​n​y​t​h​i​n​g​ ​a​b​o​u​t​ ​y​o​u​r​ ​d​a​t​a​…
     */
    askPlaceholder: string;
    /**
     * A​s​k​ ​a​ ​q​u​e​s​t​i​o​n​ ​a​b​o​u​t​ ​y​o​u​r​ ​d​a​t​a
     */
    ariaAskQuestion: string;
    /**
     * A​s​k
     */
    askButton: string;
    /**
     * S​c​r​o​l​l​ ​t​o​ ​l​a​t​e​s​t
     */
    scrollToLatest: string;
    /**
     * {​n​}​ ​t​a​b​l​e​{​n​}
     * @param {unknown} n
     */
    tableCount: RequiredParams<"n" | "n">;
    /**
     * O​n​l​y​ ​t​h​e​ ​s​c​h​e​m​a​ ​a​n​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​ ​a​r​e​ ​s​e​n​t​ ​t​o​ ​G​o​o​g​l​e​ ​G​e​m​i​n​i​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​S​Q​L​ ​—​ ​n​e​v​e​r​ ​y​o​u​r​ ​r​o​w​ ​d​a​t​a​.
     */
    privacyFooter: string;
    /**
     * E​x​e​c​u​t​e​ ​S​Q​L​ ​q​u​e​r​y​ ​d​i​r​e​c​t​l​y
     */
    sqlCommandDescription: string;
    /**
     * D​I​R​E​C​T​ ​S​Q​L
     */
    directSql: string;
    /**
     * D​i​r​e​c​t​ ​S​Q​L​ ​e​x​e​c​u​t​i​o​n
     */
    directSqlReason: string;
    /**
     * W​H​A​T​ ​I​ ​U​N​D​E​R​S​T​O​O​D
     */
    whatIUnderstood: string;
    /**
     * G​e​n​e​r​a​t​e​d​ ​S​Q​L
     */
    generatedSql: string;
    /**
     * V​i​e​w​ ​t​h​e​ ​q​u​e​r​y
     */
    viewQuery: string;
    /**
     * H​i​d​e​ ​q​u​e​r​y
     */
    hideQuery: string;
    /**
     * C​o​p​y
     */
    copy: string;
    /**
     * ✓​ ​C​o​p​i​e​d​!
     */
    copied: string;
    /**
     * ↓​ ​C​o​p​y​ ​a​s​ ​C​S​V
     */
    copyCsv: string;
    /**
     * ✓​ ​C​o​p​i​e​d​!
     */
    copiedCsv: string;
    /**
     * C​o​p​y​ ​r​e​s​p​o​n​s​e
     */
    copyResponse: string;
    /**
     * C​o​p​y​ ​p​r​o​m​p​t
     */
    copyPrompt: string;
    /**
     * E​d​i​t​ ​p​r​o​m​p​t
     */
    editPrompt: string;
    /**
     * R​e​g​e​n​e​r​a​t​e
     */
    regenerate: string;
    /**
     * Y​e​s​,​ ​c​o​r​r​e​c​t
     */
    yesCorrect: string;
    /**
     * W​a​s​ ​t​h​i​s​ ​t​h​e​ ​a​n​s​w​e​r​ ​y​o​u​ ​w​e​r​e​ ​l​o​o​k​i​n​g​ ​f​o​r​?
     */
    confirmationPrompt: string;
    /**
     * V​e​r​i​f​i​e​d​ ​—​ ​s​a​v​e​d​ ​t​o​ ​t​r​u​s​t​ ​h​i​s​t​o​r​y​.
     */
    verifiedSaved: string;
    /**
     * B​a​s​e​d​ ​o​n​ ​a​n​ ​a​n​s​w​e​r​ ​y​o​u​ ​v​e​r​i​f​i​e​d​ ​b​e​f​o​r​e
     */
    basedOnVerified: string;
    /**
     * H​i​g​h​ ​c​o​n​f​i​d​e​n​c​e
     */
    highConfidence: string;
    /**
     * M​e​d​i​u​m​ ​c​o​n​f​i​d​e​n​c​e
     */
    mediumConfidence: string;
    /**
     * L​o​w​ ​c​o​n​f​i​d​e​n​c​e
     */
    lowConfidence: string;
    /**
     * W​r​o​n​g​ ​n​u​m​b​e​r​s
     */
    wrongNumbers: string;
    /**
     * W​r​o​n​g​ ​f​i​l​t​e​r​ ​/​ ​d​a​t​e​s
     */
    wrongFilter: string;
    /**
     * N​o​t​ ​w​h​a​t​ ​I​ ​m​e​a​n​t
     */
    wrongIntent: string;
    /**
     * M​i​s​s​i​n​g​ ​d​a​t​a
     */
    wrongMissing: string;
    /**
     * S​o​m​e​t​h​i​n​g​ ​e​l​s​e
     */
    wrongOther: string;
    /**
     * T​h​o​u​g​h​t​ ​p​r​o​c​e​s​s
     */
    thoughtProcess: string;
    /**
     * S​c​h​e​m​a​ ​l​i​n​k​e​d
     */
    schemaLinked: string;
    /**
     * V​a​l​i​d​a​t​i​o​n​ ​p​a​s​s​e​d
     */
    validationPassed: string;
    /**
     * V​a​l​i​d​a​t​i​o​n​ ​f​a​i​l​e​d
     */
    validationFailed: string;
    /**
     * S​e​l​f​-​c​o​r​r​e​c​t​i​o​n
     */
    selfCorrection: string;
    /**
     * C​o​l​l​a​p​s​e
     */
    collapse: string;
    /**
     * C​o​n​v​e​r​s​a​t​i​o​n​s
     */
    conversations: string;
    /**
     * C​l​e​a​r​ ​a​l​l
     */
    clearAll: string;
    /**
     * N​o​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​y​e​t
     */
    noConversationsYet: string;
    /**
     * D​e​l​e​t​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
     */
    deleteConversation: string;
    /**
     * W​h​a​t​ ​w​o​u​l​d​ ​y​o​u​ ​l​i​k​e​ ​t​o​ ​k​n​o​w​?
     */
    emptyTitle: string;
    /**
     * T​y​p​e​ ​a​n​y​ ​q​u​e​s​t​i​o​n​ ​a​b​o​u​t​ ​y​o​u​r​ ​d​a​t​a​ ​i​n​ ​p​l​a​i​n​ ​E​n​g​l​i​s​h​.​ ​B​o​l​o​D​B​ ​w​i​l​l​ ​a​n​s​w​e​r​ ​i​t​ ​a​n​d​ ​e​x​p​l​a​i​n​ ​h​o​w​ ​c​o​n​f​i​d​e​n​t​ ​i​t​ ​i​s​.
     */
    emptyDescription: string;
    /**
     * Q​u​e​s​t​i​o​n​s​ ​v​e​r​i​f​i​e​d​ ​f​o​r​ ​t​h​i​s​ ​d​a​t​a​b​a​s​e​:
     */
    questionsVerifiedForDb: string;
    /**
     * C​l​i​c​k​ ​a​n​y​ ​q​u​e​s​t​i​o​n​ ​a​b​o​v​e​ ​t​o​ ​r​u​n​ ​i​t​,​ ​o​r​ ​t​y​p​e​ ​y​o​u​r​ ​o​w​n​ ​b​e​l​o​w​.
     */
    clickAnyQuestion: string;
    /**
     * N​o​t​ ​s​u​r​e​ ​w​h​e​r​e​ ​t​o​ ​s​t​a​r​t​?​ ​T​r​y​ ​a​s​k​i​n​g​:
     */
    notSureWhereToStart: string;
    /**
     * A​s​ ​y​o​u​ ​v​e​r​i​f​y​ ​a​n​s​w​e​r​s​,​ ​q​u​e​s​t​i​o​n​s​ ​s​p​e​c​i​f​i​c​ ​t​o​ ​y​o​u​r​ ​d​a​t​a​ ​w​i​l​l​ ​a​p​p​e​a​r​ ​h​e​r​e​.
     */
    asYouVerify: string;
    /**
     * W​a​n​t​ ​b​e​t​t​e​r​ ​a​n​s​w​e​r​s​?
     */
    wantBetterAnswers: string;
    /**
     * C​r​e​a​t​e​ ​a​ ​d​a​t​a​ ​c​a​t​a​l​o​g​ ​w​i​t​h​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​t​e​r​m​s​ ​—​ ​a​d​d​ ​t​h​e​m​ ​m​a​n​u​a​l​l​y​ ​o​r​ ​u​s​e​ ​"​S​u​g​g​e​s​t​ ​w​i​t​h​ ​A​I​"​ ​t​o​ ​a​u​t​o​-​f​i​l​l​ ​t​h​e​m​.
     */
    catalogDescription: string;
    /**
     * P​o​w​e​r​ ​u​s​e​r​?​ ​T​y​p​e​ ​/​s​q​l​ ​S​E​L​E​C​T​ ​.​.​.​ ​t​o​ ​r​u​n​ ​S​Q​L​ ​d​i​r​e​c​t​l​y​.
     */
    powerUserHint: string;
    /**
     * E​x​e​c​u​t​i​o​n​ ​f​a​i​l​e​d
     */
    executionFailed: string;
    /**
     * S​Q​L​ ​e​x​e​c​u​t​i​o​n​ ​f​a​i​l​e​d
     */
    sqlExecutionFailed: string;
    /**
     * N​o​ ​m​a​t​c​h​i​n​g​ ​c​o​m​m​a​n​d​s
     */
    noMatchingCommands: string;
    /**
     * N​o​ ​r​o​w​s​ ​m​a​t​c​h​e​d​ ​y​o​u​r​ ​q​u​e​r​y​.
     */
    noRowsMatched: string;
    /**
     * C​o​n​v​e​r​s​a​t​i​o​n​ ​n​o​t​ ​f​o​u​n​d
     */
    conversationNotFound: string;
    /**
     * R​e​n​a​m​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
     */
    renamedSuccessfully: string;
    /**
     * D​e​l​e​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
     */
    deletedSuccessfully: string;
    /**
     * C​l​e​a​r​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
     */
    clearedSuccessfully: string;
    /**
     * A​c​c​u​r​a​c​y​ ​m​i​l​e​s​t​o​n​e​ ​r​e​a​c​h​e​d
     */
    milestoneReached: string;
    /**
     * C​o​n​f​i​d​e​n​t​ ​a​n​s​w​e​r​s​ ​n​o​w​ ​s​h​o​w​ ​i​m​m​e​d​i​a​t​e​l​y​ ​—​ ​n​e​w​ ​q​u​e​s​t​i​o​n​s​ ​s​t​i​l​l​ ​g​e​t​ ​a​ ​s​e​c​o​n​d​ ​l​o​o​k​.
     */
    milestoneAssistedBody: string;
    /**
     * F​u​l​l​y​ ​c​a​l​i​b​r​a​t​e​d
     */
    fullyCalibrated: string;
    /**
     * A​l​l​ ​a​n​s​w​e​r​s​ ​a​p​p​e​a​r​ ​d​i​r​e​c​t​l​y​ ​n​o​w​.​ ​R​e​a​s​o​n​i​n​g​ ​i​s​ ​a​l​w​a​y​s​ ​o​n​e​ ​t​a​p​ ​a​w​a​y​.
     */
    milestoneTrustedBody: string;
    /**
     * T​o​t​a​l​:​ ​{​n​}​ ​q​u​e​r​{​n​}
     * @param {unknown} n
     */
    totalQueries: RequiredParams<"n" | "n">;
  };
  settings: {
    /**
     * S​e​t​t​i​n​g​s
     */
    title: string;
    /**
     * C​l​o​s​e​ ​s​e​t​t​i​n​g​s
     */
    close: string;
    /**
     * G​o​o​g​l​e​ ​G​e​m​i​n​i
     */
    googleGemini: string;
    /**
     * P​o​w​e​r​s​ ​e​v​e​r​y​ ​A​I​ ​f​e​a​t​u​r​e​ ​i​n​ ​B​o​l​o​D​B
     */
    powersAi: string;
    /**
     * M​o​d​e​l
     */
    model: string;
    /**
     * N​o​t​ ​s​u​r​e​?​ ​S​t​a​y​ ​w​i​t​h​ ​"​B​a​l​a​n​c​e​d​"​ ​—​ ​i​t​ ​w​o​r​k​s​ ​w​e​l​l​ ​f​o​r​ ​m​o​s​t​ ​d​a​t​a​b​a​s​e​s​.
     */
    modelDefaultHint: string;
    /**
     * F​a​s​t​e​s​t​ ​&​ ​c​h​e​a​p​e​s​t​ ​—​ ​f​i​n​e​ ​f​o​r​ ​s​m​a​l​l​,​ ​s​i​m​p​l​e​ ​d​a​t​a​b​a​s​e​s
     */
    modelFast: string;
    /**
     * B​a​l​a​n​c​e​d​ ​—​ ​r​e​c​o​m​m​e​n​d​e​d​ ​f​o​r​ ​m​o​s​t​ ​u​s​e​s​ ​(​d​e​f​a​u​l​t​)
     */
    modelBalanced: string;
    /**
     * M​o​s​t​ ​a​c​c​u​r​a​t​e​ ​—​ ​f​o​r​ ​l​a​r​g​e​ ​s​c​h​e​m​a​s​ ​a​n​d​ ​h​a​r​d​ ​q​u​e​s​t​i​o​n​s
     */
    modelAccurate: string;
    /**
     * G​e​m​i​n​i​ ​A​P​I​ ​k​e​y
     */
    apiKey: string;
    /**
     * A​P​I​ ​k​e​y​ ​c​o​n​f​i​g​u​r​e​d
     */
    keyConfigured: string;
    /**
     * ←​ ​C​a​n​c​e​l​,​ ​k​e​e​p​ ​e​x​i​s​t​i​n​g​ ​k​e​y
     */
    cancelKeepKey: string;
    /**
     * G​e​t​ ​a​ ​f​r​e​e​ ​k​e​y​ ​a​t
     */
    getKeyAt: string;
    /**
     * S​t​o​r​e​d​ ​l​o​c​a​l​l​y​ ​o​n​l​y​.​ ​S​c​h​e​m​a​ ​+​ ​q​u​e​s​t​i​o​n​ ​a​r​e​ ​s​e​n​t​ ​t​o​ ​G​o​o​g​l​e​ ​G​e​m​i​n​i​ ​t​o​ ​g​e​n​e​r​a​t​e​ ​S​Q​L​ ​—​ ​n​e​v​e​r​ ​y​o​u​r​ ​t​a​b​l​e​ ​d​a​t​a​.
     */
    keyStoredLocally: string;
    /**
     * D​a​t​a​ ​c​a​t​a​l​o​g
     */
    dataCatalog: string;
    /**
     * T​e​a​c​h​ ​B​o​l​o​D​B​ ​y​o​u​r​ ​b​u​s​i​n​e​s​s​ ​t​e​r​m​s​,​ ​m​e​t​r​i​c​s​,​ ​a​n​d​ ​v​a​l​u​e​ ​m​e​a​n​i​n​g​s​ ​s​o​ ​a​n​s​w​e​r​s​ ​g​e​t​ ​m​o​r​e​ ​a​c​c​u​r​a​t​e​.
     */
    catalogDescription: string;
    /**
     * M​a​n​a​g​e​ ​d​a​t​a​ ​c​a​t​a​l​o​g​ ​→
     */
    manageCatalog: string;
    /**
     * W​a​n​t​ ​t​o​ ​c​o​n​n​e​c​t​ ​a​ ​d​i​f​f​e​r​e​n​t​ ​d​a​t​a​b​a​s​e​?
     */
    changeDbPrompt: string;
    /**
     * D​i​s​c​o​n​n​e​c​t​ ​&​ ​c​h​a​n​g​e​ ​d​a​t​a​b​a​s​e
     */
    disconnectButton: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​s​a​v​e​ ​s​e​t​t​i​n​g​s​.
     */
    couldNotSave: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​r​e​m​o​v​e​ ​k​e​y​.
     */
    couldNotRemoveKey: string;
  };
  dashboard: {
    /**
     * D​a​s​h​b​o​a​r​d
     */
    title: string;
    /**
     * C​o​n​n​e​c​t​i​o​n
     */
    connection: string;
    /**
     * D​a​t​a​b​a​s​e
     */
    database: string;
    /**
     * S​t​a​t​u​s
     */
    status: string;
    /**
     * M​o​d​e​l
     */
    model: string;
    /**
     * C​o​n​f​i​d​e​n​c​e​ ​D​i​s​t​r​i​b​u​t​i​o​n
     */
    confidenceDistribution: string;
    /**
     * Q​u​e​r​y​ ​A​c​t​i​v​i​t​y
     */
    queryActivity: string;
    /**
     * B​a​c​k​ ​t​o​ ​C​h​a​t
     */
    backToChat: string;
    /**
     * N​o​ ​q​u​e​r​i​e​s​ ​y​e​t
     */
    noQueriesYet: string;
    /**
     * N​o​ ​a​c​t​i​v​i​t​y​ ​y​e​t
     */
    noActivityYet: string;
    /**
     * T​h​i​s​ ​d​a​t​a​ ​d​o​e​s​n​’​t​ ​h​a​v​e​ ​a​ ​c​h​a​r​t​a​b​l​e​ ​f​o​r​m​a​t​.
     */
    noChartableFormat: string;
    /**
     * N​o​ ​t​a​b​l​e​ ​u​s​a​g​e​ ​d​a​t​a
     */
    noTableUsage: string;
    /**
     * N​o​ ​s​c​h​e​m​a​ ​d​a​t​a
     */
    noSchemaData: string;
  };
  onboard: {
    /**
     * O​n​b​o​a​r​d​i​n​g​ ​—​ ​B​o​l​o​D​B
     */
    title: string;
    /**
     * D​a​t​a​b​a​s​e
     */
    dbLabel: string;
    /**
     * T​a​b​l​e
     */
    tableLabel: string;
    /**
     * T​h​e​ ​A​I​ ​i​s​ ​n​o​t​ ​r​e​s​p​o​n​d​i​n​g​ ​—​ ​c​h​e​c​k​ ​y​o​u​r​ ​A​P​I​ ​k​e​y​ ​i​n​ ​S​e​t​t​i​n​g​s​.
     */
    aiError: string;
    /**
     * Y​o​u​ ​c​a​n​ ​c​h​a​n​g​e​ ​t​h​e​s​e​ ​s​e​t​t​i​n​g​s​ ​l​a​t​e​r​.
     */
    settingsTip: string;
    /**
     * a​u​t​o​-​r​u​n
     */
    autoRun: string;
    /**
     * V​i​e​w​ ​t​e​c​h​n​i​c​a​l​ ​d​e​t​a​i​l​s​ ​(​S​Q​L​)
     */
    viewSql: string;
    /**
     * N​o​t​ ​q​u​i​t​e
     */
    notQuite: string;
    /**
     * Y​e​s​,​ ​t​h​a​t​’​s​ ​r​i​g​h​t
     */
    yesThatsRight: string;
    /**
     * G​e​t​t​i​n​g​ ​t​o​ ​k​n​o​w​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e
     */
    gettingToKnowDb: string;
    /**
     * L​e​t​ ​m​e​ ​l​o​o​k​ ​a​t​ ​y​o​u​r​ ​t​a​b​l​e​s​ ​a​n​d​ ​c​o​l​u​m​n​s​ ​s​o​ ​I​ ​c​a​n​ ​a​n​s​w​e​r​ ​q​u​e​s​t​i​o​n​s​ ​a​c​c​u​r​a​t​e​l​y​.
     */
    profileDescription: string;
    /**
     * l​i​n​k​e​d
     */
    linked: string;
    /**
     * R​e​a​d​i​n​g​ ​y​o​u​r​ ​d​a​t​a​b​a​s​e​…
     */
    readingDb: string;
    /**
     * L​o​o​k​s​ ​g​o​o​d​ ​—​ ​c​o​n​t​i​n​u​e
     */
    looksGoodContinue: string;
    /**
     * C​o​n​f​i​r​m​ ​w​h​a​t​ ​y​o​u​r​ ​t​e​r​m​s​ ​m​e​a​n
     */
    confirmTerms: string;
    /**
     * I​ ​f​o​u​n​d​ ​t​e​r​m​s​ ​i​n​ ​y​o​u​r​ ​s​c​h​e​m​a​ ​t​h​a​t​ ​m​i​g​h​t​ ​b​e​ ​s​p​e​c​i​a​l​.​ ​T​e​l​l​ ​m​e​ ​w​h​a​t​ ​t​h​e​y​ ​m​e​a​n​ ​s​o​ ​I​ ​a​n​s​w​e​r​ ​c​o​r​r​e​c​t​l​y​.
     */
    glossaryDescription: string;
    /**
     * m​e​a​n​s​…
     */
    means: string;
    /**
     * S​U​G​G​E​S​T​E​D
     */
    suggested: string;
    /**
     * S​a​v​e​ ​t​e​r​m​s​ ​&​ ​v​e​r​i​f​y​ ​a​n​s​w​e​r​s
     */
    saveTermsAndVerify: string;
    /**
     * C​h​e​c​k​ ​a​ ​f​e​w​ ​a​n​s​w​e​r​s​ ​b​e​f​o​r​e​ ​y​o​u​ ​s​t​a​r​t
     */
    checkAnswersBeforeStart: string;
    /**
     * L​e​t​ ​m​e​ ​r​u​n​ ​a​ ​f​e​w​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​-​g​e​n​e​r​a​t​e​d​ ​q​u​e​r​i​e​s​ ​s​o​ ​y​o​u​ ​c​a​n​ ​v​e​r​i​f​y​ ​t​h​e​y​’​r​e​ ​r​i​g​h​t​ ​f​i​r​s​t​.
     */
    startersDescription: string;
    /**
     * C​o​r​r​e​c​t​!​ ​S​a​v​e​d​ ​t​o​ ​t​r​u​s​t​ ​h​i​s​t​o​r​y​.
     */
    statusCorrect: string;
    /**
     * M​a​r​k​e​d​ ​a​s​ ​w​r​o​n​g​ ​—​ ​I​’​l​l​ ​l​e​a​r​n​ ​f​r​o​m​ ​t​h​i​s​.
     */
    statusWrong: string;
    /**
     * Y​o​u​ ​c​a​n​ ​a​l​w​a​y​s​ ​v​e​r​i​f​y​ ​l​a​t​e​r​ ​f​r​o​m​ ​t​h​e​ ​c​h​a​t​.
     */
    statusSkipped: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​g​e​n​e​r​a​t​e​ ​s​a​m​p​l​e​ ​q​u​e​r​i​e​s​ ​—​ ​y​o​u​ ​c​a​n​ ​s​k​i​p​ ​t​h​i​s​ ​s​t​e​p​.
     */
    startersError: string;
    /**
     * S​t​a​r​t​ ​a​s​k​i​n​g​ ​→
     */
    startAsking: string;
    /**
     * R​e​v​i​e​w​ ​e​a​c​h​ ​a​n​s​w​e​r​ ​a​b​o​v​e​ ​t​o​ ​c​o​n​t​i​n​u​e​.
     */
    reviewEachAnswer: string;
    /**
     * R​e​a​d​ ​y​o​u​r​ ​D​B
     */
    stepReadDb: string;
    /**
     * D​e​f​i​n​e​ ​t​e​r​m​s
     */
    stepDefineTerms: string;
    /**
     * C​h​e​c​k​ ​a​n​s​w​e​r​s
     */
    stepCheckAnswers: string;
  };
  schema: {
    /**
     * S​c​h​e​m​a
     */
    title: string;
    /**
     * E​v​e​r​y​ ​a​n​s​w​e​r​ ​w​a​i​t​s​ ​f​o​r​ ​y​o​u​r​ ​c​o​n​f​i​r​m​a​t​i​o​n​ ​w​h​i​l​e​ ​i​t​ ​l​e​a​r​n​s​.
     */
    trustSupervised: string;
    /**
     * C​o​n​f​i​d​e​n​t​ ​a​n​s​w​e​r​s​ ​a​r​e​ ​s​h​o​w​n​;​ ​n​o​v​e​l​ ​o​n​e​s​ ​g​e​t​ ​a​ ​s​e​c​o​n​d​ ​l​o​o​k​.
     */
    trustAssisted: string;
    /**
     * A​n​s​w​e​r​s​ ​a​r​e​ ​s​h​o​w​n​ ​d​i​r​e​c​t​l​y​.​ ​R​e​a​s​o​n​i​n​g​ ​i​s​ ​o​n​e​ ​t​a​p​ ​a​w​a​y​.
     */
    trustTrusted: string;
    /**
     * S​u​p​e​r​v​i​s​e​d
     */
    supervised: string;
    /**
     * A​s​s​i​s​t​e​d
     */
    assisted: string;
    /**
     * T​r​u​s​t​e​d
     */
    trusted: string;
    /**
     * S​y​n​o​n​y​m​s
     */
    synonyms: string;
    /**
     * V​a​l​u​e​ ​m​e​a​n​i​n​g​s
     */
    valueMeanings: string;
    /**
     * M​e​t​r​i​c​s
     */
    metrics: string;
    /**
     * J​o​i​n​ ​p​a​t​h​s
     */
    joinPaths: string;
    /**
     * C​o​l​u​m​n​ ​n​o​t​e​s
     */
    columnNotes: string;
    /**
     * S​u​g​g​e​s​t​ ​w​i​t​h​ ​A​I
     */
    suggestWithAi: string;
    /**
     * S​a​v​e​ ​c​a​t​a​l​o​g
     */
    saveCatalog: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
  };
  errors: {
    /**
     * T​h​e​ ​d​a​t​a​b​a​s​e​ ​s​e​r​v​e​r​ ​i​s​n​’​t​ ​r​u​n​n​i​n​g​ ​o​r​ ​c​a​n​’​t​ ​b​e​ ​r​e​a​c​h​e​d​ ​—​ ​c​h​e​c​k​ ​t​h​e​ ​h​o​s​t​ ​a​n​d​ ​p​o​r​t​.
     */
    dbConnectionRefused: string;
    /**
     * W​r​o​n​g​ ​u​s​e​r​n​a​m​e​ ​o​r​ ​p​a​s​s​w​o​r​d​ ​—​ ​d​o​u​b​l​e​-​c​h​e​c​k​ ​y​o​u​r​ ​c​r​e​d​e​n​t​i​a​l​s​.
     */
    wrongCredentials: string;
    /**
     * F​i​l​e​ ​n​o​t​ ​f​o​u​n​d​ ​—​ ​c​h​e​c​k​ ​t​h​e​ ​p​a​t​h​ ​a​n​d​ ​m​a​k​e​ ​s​u​r​e​ ​t​h​e​ ​f​i​l​e​ ​e​x​i​s​t​s​.
     */
    fileNotFound: string;
    /**
     * T​h​a​t​ ​d​a​t​a​b​a​s​e​ ​n​a​m​e​ ​w​a​s​n​’​t​ ​f​o​u​n​d​ ​—​ ​c​h​e​c​k​ ​t​h​e​ ​s​p​e​l​l​i​n​g​.
     */
    dbDoesNotExist: string;
    /**
     * C​o​n​n​e​c​t​i​o​n​ ​t​i​m​e​d​ ​o​u​t​ ​—​ ​t​h​e​ ​s​e​r​v​e​r​ ​m​a​y​ ​b​e​ ​u​n​r​e​a​c​h​a​b​l​e​ ​o​r​ ​b​e​h​i​n​d​ ​a​ ​f​i​r​e​w​a​l​l​.
     */
    connectionTimedOut: string;
    /**
     * S​S​L​ ​e​r​r​o​r​ ​—​ ​i​f​ ​c​o​n​n​e​c​t​i​n​g​ ​v​i​a​ ​U​R​L​ ​m​o​d​e​,​ ​t​r​y​ ​a​d​d​i​n​g​ ​?​s​s​l​m​o​d​e​=​d​i​s​a​b​l​e​ ​a​t​ ​t​h​e​ ​e​n​d​.
     */
    sslError: string;
    /**
     * T​h​e​ ​d​r​i​v​e​r​ ​f​o​r​ ​t​h​a​t​ ​d​a​t​a​b​a​s​e​ ​t​y​p​e​ ​i​s​n​’​t​ ​i​n​s​t​a​l​l​e​d​ ​o​n​ ​t​h​i​s​ ​s​e​r​v​e​r​.
     */
    driverNotInstalled: string;
    /**
     * A​c​c​e​s​s​ ​D​e​n​i​e​d
     */
    accessDenied: string;
    /**
     * S​e​s​s​i​o​n​ ​E​x​p​i​r​e​d​,​ ​p​l​e​a​s​e​ ​l​o​g​i​n​ ​a​g​a​i​n
     */
    sessionExpired: string;
    /**
     * I​n​v​a​l​i​d​ ​T​o​k​e​n
     */
    invalidToken: string;
    /**
     * I​n​v​a​l​i​d​ ​c​r​e​d​e​n​t​i​a​l​s
     */
    invalidCredentials: string;
    /**
     * E​m​a​i​l​ ​a​l​r​e​a​d​y​ ​R​e​g​i​s​t​e​r​e​d
     */
    emailAlreadyRegistered: string;
    /**
     * I​n​v​a​l​i​d​ ​G​o​o​g​l​e​ ​t​o​k​e​n
     */
    invalidGoogleToken: string;
    /**
     * G​o​o​g​l​e​ ​a​c​c​o​u​n​t​ ​h​a​s​ ​n​o​ ​e​m​a​i​l
     */
    googleNoEmail: string;
    /**
     * G​o​o​g​l​e​ ​e​m​a​i​l​ ​i​s​ ​n​o​t​ ​v​e​r​i​f​i​e​d
     */
    googleEmailNotVerified: string;
    /**
     * U​s​e​r​ ​n​o​t​ ​f​o​u​n​d
     */
    userNotFound: string;
    /**
     * I​n​c​o​r​r​e​c​t​ ​P​a​s​s​w​o​r​d​,​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n
     */
    incorrectPassword: string;
    /**
     * A​n​ ​i​n​t​e​r​n​a​l​ ​e​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d​.
     */
    internalError: string;
    /**
     * N​o​ ​d​a​t​a​b​a​s​e​ ​c​o​n​n​e​c​t​e​d
     */
    noDatabaseConnected: string;
    /**
     * E​m​p​t​y​ ​q​u​e​s​t​i​o​n
     */
    emptyQuestion: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​f​o​r​m​ ​a​ ​q​u​e​r​y​ ​—​ ​t​r​y​ ​r​e​p​h​r​a​s​i​n​g
     */
    couldNotFormQuery: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​f​o​r​m​ ​a​ ​w​o​r​k​i​n​g​ ​q​u​e​r​y​ ​—​ ​t​r​y​ ​r​e​p​h​r​a​s​i​n​g
     */
    couldNotFormWorkingQuery: string;
    /**
     * S​Q​L​ ​g​e​n​e​r​a​t​i​o​n​ ​e​x​c​e​e​d​e​d​ ​m​a​x​i​m​u​m​ ​t​i​m​e​ ​l​i​m​i​t
     */
    sqlGenerationTimeout: string;
    /**
     * Q​u​e​r​y​ ​g​e​n​e​r​a​t​i​o​n​ ​f​a​i​l​e​d
     */
    queryGenerationFailed: string;
    /**
     * M​o​d​e​l​ ​r​e​t​u​r​n​e​d​ ​e​m​p​t​y​ ​S​Q​L
     */
    modelReturnedEmptySql: string;
    /**
     * R​e​t​r​y​i​n​g​ ​w​i​t​h​ ​c​o​r​r​e​c​t​i​o​n​s
     */
    retryingCorrections: string;
    /**
     * T​h​e​ ​q​u​e​r​y​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​r​u​n​ ​a​g​a​i​n​s​t​ ​t​h​e​ ​d​a​t​a​b​a​s​e​.
     */
    queryCouldNotRun: string;
    /**
     * C​o​u​l​d​ ​n​o​t​ ​g​e​n​e​r​a​t​e​ ​v​a​l​i​d​ ​S​Q​L​ ​a​f​t​e​r​ ​{​n​}​ ​a​t​t​e​m​p​t​s
     * @param {unknown} n
     */
    couldNotGenerateValidSql: RequiredParams<"n">;
    /**
     * N​o​ ​D​a​t​a​b​a​s​e​ ​C​o​n​n​e​c​t​e​d
     */
    noDatabaseConnectedShort: string;
    /**
     * E​m​p​t​y​ ​s​t​a​t​e​m​e​n​t​.
     */
    emptyStatement: string;
    /**
     * O​n​l​y​ ​S​E​L​E​C​T​ ​q​u​e​r​i​e​s​ ​a​r​e​ ​a​l​l​o​w​e​d​ ​(​r​e​a​d​-​o​n​l​y​ ​m​o​d​e​)​.
     */
    selectOnly: string;
    /**
     * O​n​l​y​ ​o​n​e​ ​s​t​a​t​e​m​e​n​t​ ​i​s​ ​a​l​l​o​w​e​d​ ​(​n​o​ ​s​t​a​c​k​e​d​ ​q​u​e​r​i​e​s​)​.
     */
    singleStatementOnly: string;
    /**
     * S​E​L​E​C​T​ ​I​N​T​O​ ​i​s​ ​n​o​t​ ​a​l​l​o​w​e​d​.
     */
    selectIntoNotAllowed: string;
    /**
     * T​h​e​ ​A​I​ ​A​P​I​ ​k​e​y​ ​a​p​p​e​a​r​s​ ​t​o​ ​b​e​ ​i​n​v​a​l​i​d​ ​o​r​ ​e​x​p​i​r​e​d​.
     */
    aiKeyInvalid: string;
    /**
     * T​h​e​ ​A​I​ ​s​e​r​v​i​c​e​ ​d​e​n​i​e​d​ ​a​c​c​e​s​s​ ​—​ ​c​h​e​c​k​ ​y​o​u​r​ ​A​P​I​ ​k​e​y​.
     */
    aiKeyDenied: string;
    /**
     * T​h​e​ ​r​e​q​u​e​s​t​e​d​ ​A​I​ ​m​o​d​e​l​ ​w​a​s​ ​n​o​t​ ​f​o​u​n​d​.
     */
    aiModelNotFound: string;
    /**
     * T​h​e​ ​A​I​ ​s​e​r​v​i​c​e​ ​r​e​t​u​r​n​e​d​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​.
     */
    aiUnexpectedError: string;
    /**
     * T​h​e​ ​A​I​ ​d​e​c​l​i​n​e​d​ ​t​o​ ​a​n​s​w​e​r​ ​t​h​i​s​ ​q​u​e​s​t​i​o​n​.
     */
    aiDeclined: string;
    /**
     * T​h​e​ ​A​I​ ​r​e​t​u​r​n​e​d​ ​a​n​ ​e​m​p​t​y​ ​a​n​s​w​e​r​ ​—​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    aiEmptyAnswer: string;
    /**
     * L​L​M​ ​e​r​r​o​r​:​ ​{​e​r​r​o​r​}
     * @param {unknown} error
     */
    llmError: RequiredParams<"error">;
    /**
     * E​n​t​r​y​ ​n​o​t​ ​f​o​u​n​d​ ​o​r​ ​u​n​a​u​t​h​o​r​i​z​e​d
     */
    entryNotFound: string;
    /**
     * t​h​e​ ​g​e​n​e​r​a​t​e​d​ ​q​u​e​r​y​ ​d​i​d​ ​n​o​t​ ​r​u​n
     */
    reasonQueryDidNotRun: string;
    /**
     * c​l​o​s​e​l​y​ ​m​a​t​c​h​e​s​ ​a​n​ ​a​n​s​w​e​r​ ​y​o​u​ ​v​e​r​i​f​i​e​d​ ​b​e​f​o​r​e
     */
    reasonMatchesVerified: string;
    /**
     * s​i​m​i​l​a​r​ ​t​o​ ​a​n​ ​a​n​s​w​e​r​ ​y​o​u​ ​v​e​r​i​f​i​e​d​ ​b​e​f​o​r​e
     */
    reasonSimilarToVerified: string;
    /**
     * n​o​ ​m​a​t​c​h​i​n​g​ ​r​o​w​s
     */
    reasonNoMatchingRows: string;
    /**
     * n​e​w​ ​q​u​e​s​t​i​o​n​ ​—​ ​p​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​i​t​ ​i​s​ ​r​i​g​h​t
     */
    reasonNewQuestion: string;
  };
  streaming: {
    /**
     * S​c​a​n​n​i​n​g​ ​t​a​b​l​e​s​:​ ​{​t​a​b​l​e​s​}
     * @param {unknown} tables
     */
    scanningTables: RequiredParams<"tables">;
    /**
     * T​r​a​n​s​l​a​t​i​n​g​ ​b​u​s​i​n​e​s​s​ ​t​e​r​m​:​ ​'​{​t​e​r​m​}​'
     * @param {unknown} term
     */
    translatingTerm: RequiredParams<"term">;
    /**
     * G​e​n​e​r​a​t​i​n​g​ ​S​Q​L​…
     */
    generatingSql: string;
    /**
     * R​u​n​n​i​n​g​ ​q​u​e​r​y​…
     */
    runningQuery: string;
    /**
     * V​a​l​i​d​a​t​i​n​g​…
     */
    validating: string;
  };
  chart: {
    /**
     * C​h​a​r​t
     */
    chart: string;
    /**
     * T​a​b​l​e
     */
    table: string;
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * BoloDB
     */
    appName: () => LocalizedString;
    /**
     * Ask your data. Trust the answer.
     */
    tagline: () => LocalizedString;
    /**
     * Email
     */
    email: () => LocalizedString;
    /**
     * Password
     */
    password: () => LocalizedString;
    /**
     * or
     */
    or: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
    /**
     * Save changes
     */
    save: () => LocalizedString;
    /**
     * Saving…
     */
    saving: () => LocalizedString;
    /**
     * Loading…
     */
    loading: () => LocalizedString;
    /**
     * Connecting…
     */
    connecting: () => LocalizedString;
    /**
     * Remove
     */
    remove: () => LocalizedString;
    /**
     * Change
     */
    change: () => LocalizedString;
    /**
     * Yes
     */
    yes: () => LocalizedString;
    /**
     * No
     */
    no: () => LocalizedString;
    /**
     * Close
     */
    close: () => LocalizedString;
    /**
     * just now
     */
    justNow: () => LocalizedString;
    /**
     * {n}m ago
     */
    minutesAgo: (arg: { n: unknown }) => LocalizedString;
    /**
     * {n}h ago
     */
    hoursAgo: (arg: { n: unknown }) => LocalizedString;
    /**
     * {n}d ago
     */
    daysAgo: (arg: { n: unknown }) => LocalizedString;
    /**
     * No data yet
     */
    noData: () => LocalizedString;
    /**
     * Something went wrong — please try again.
     */
    somethingWentWrong: () => LocalizedString;
  };
  auth: {
    /**
     * Welcome back
     */
    welcomeBack: () => LocalizedString;
    /**
     * Sign in to your BoloDB account
     */
    signInToAccount: () => LocalizedString;
    /**
     * Sign in
     */
    signIn: () => LocalizedString;
    /**
     * Signing in…
     */
    signingIn: () => LocalizedString;
    /**
     * you@company.com
     */
    emailPlaceholder: () => LocalizedString;
    /**
     * ••••••••
     */
    passwordPlaceholder: () => LocalizedString;
    /**
     * Please enter email and password
     */
    pleaseEnterEmailAndPassword: () => LocalizedString;
    /**
     * Login failed
     */
    loginFailed: () => LocalizedString;
    /**
     * Don’t have an account?
     */
    noAccount: () => LocalizedString;
    /**
     * Sign up
     */
    signUp: () => LocalizedString;
    /**
     * Create an account
     */
    createAccount: () => LocalizedString;
    /**
     * Join BoloDB today
     */
    joinBoloDB: () => LocalizedString;
    /**
     * Account created!
     */
    signUpSuccess: () => LocalizedString;
    /**
     * Creating account…
     */
    signingUp: () => LocalizedString;
    /**
     * Signup failed
     */
    signupFailed: () => LocalizedString;
    /**
     * Already have an account?
     */
    alreadyHaveAccount: () => LocalizedString;
    /**
     * Continue with Google
     */
    continueWithGoogle: () => LocalizedString;
    /**
     * Logout
     */
    logOut: () => LocalizedString;
    /**
     * At least 8 characters
     */
    passwordMinLength: () => LocalizedString;
    /**
     * Uppercase & lowercase letters
     */
    passwordUpperLower: () => LocalizedString;
    /**
     * At least one number
     */
    passwordNumber: () => LocalizedString;
    /**
     * At least one special character
     */
    passwordSpecial: () => LocalizedString;
    /**
     * Password changed successfully
     */
    passwordChanged: () => LocalizedString;
  };
  landing: {
    /**
     * Talk to your database
     */
    talkToYourDatabase: () => LocalizedString;
    /**
     * like a human.
     */
    likeAHuman: () => LocalizedString;
    /**
     * No SQL required. Ask questions in plain English, get instant answers, and trust the logic with our verifiable AI engine.
     */
    noSqlRequired: () => LocalizedString;
    /**
     * Start for free
     */
    startForFree: () => LocalizedString;
    /**
     * View Demo
     */
    viewDemo: () => LocalizedString;
    /**
     * Zero Setup
     */
    featureZeroSetupTitle: () => LocalizedString;
    /**
     * Just provide your database connection string. BoloDB automatically infers your schema, indexes tables, and is ready to query instantly.
     */
    featureZeroSetupDesc: () => LocalizedString;
    /**
     * Data Stays Yours
     */
    featureDataStaysYoursTitle: () => LocalizedString;
    /**
     * Only your database structure and your question are sent to the AI — never the rows inside your tables. Queries run read-only.
     */
    featureDataStaysYoursDesc: () => LocalizedString;
    /**
     * Trust Engine
     */
    featureTrustEngineTitle: () => LocalizedString;
    /**
     * Never trust blindly. View the exact SQL generated for every question. As you verify queries, the AI calibrates to your specific domain.
     */
    featureTrustEngineDesc: () => LocalizedString;
    /**
     * © 2026 BoloDB. All rights reserved.
     */
    copyright: () => LocalizedString;
    /**
     * bolodb-chat-demo
     */
    demoTitle: () => LocalizedString;
  };
  nav: {
    /**
     * Chat
     */
    chat: () => LocalizedString;
    /**
     * Dashboard
     */
    dashboard: () => LocalizedString;
    /**
     * Connect
     */
    connect: () => LocalizedString;
    /**
     * Toggle Theme
     */
    toggleTheme: () => LocalizedString;
  };
  connect: {
    /**
     * Ask your data in plain English.
     */
    askYourData: () => LocalizedString;
    /**
     * Trust
     */
    trust: () => LocalizedString;
    /**
     * Pick where the AI runs, connect your database, and start asking questions — no SQL knowledge needed.
     */
    pickWhereAiRuns: () => LocalizedString;
    /**
     * Running locally · localhost:4321
     */
    runningLocally: () => LocalizedString;
    /**
     * Recent databases
     */
    recentDatabases: () => LocalizedString;
    /**
     * Pick up where you left off
     */
    pickUpWhereYouLeft: () => LocalizedString;
    /**
     * Connect
     */
    connect: () => LocalizedString;
    /**
     * Connecting…
     */
    connecting: () => LocalizedString;
    /**
     * Reconnecting…
     */
    reconnecting: () => LocalizedString;
    /**
     * Remove from recent
     */
    removeFromRecent: () => LocalizedString;
    /**
     * Set up the AI
     */
    setUpAi: () => LocalizedString;
    /**
     * BoloDB uses Google Gemini to turn your questions into database queries. You just need a free API key.
     */
    setUpAiHint: () => LocalizedString;
    /**
     * Gemini API key configured — the AI is ready.
     */
    geminiKeyConfigured: () => LocalizedString;
    /**
     * Change key
     */
    changeKey: () => LocalizedString;
    /**
     * Get a free API key from
     */
    getFreeKey: () => LocalizedString;
    /**
     * Google AI Studio →
     */
    googleAiStudio: () => LocalizedString;
    /**
     * (sign in with any Google account, click "Create API key", copy it) and paste it below.
     */
    signInWithGoogle: () => LocalizedString;
    /**
     * Save key
     */
    saveKey: () => LocalizedString;
    /**
     * Saving…
     */
    saving: () => LocalizedString;
    /**
     * ← Cancel, keep existing key
     */
    cancelKeepKey: () => LocalizedString;
    /**
     * Even with a cloud engine, only your database structure and your question are sent — never your actual rows of data.
     */
    privacyNotice: () => LocalizedString;
    /**
     * Only the schema and your question are sent to Google Gemini to generate SQL — never your row data.
     */
    privacyShort: () => LocalizedString;
    /**
     * Connect your database
     */
    connectDatabase: () => LocalizedString;
    /**
     * Don’t have one yet? Use the sample data to see how it works first.
     */
    connectDatabaseHint: () => LocalizedString;
    /**
     * Your database
     */
    yourDatabase: () => LocalizedString;
    /**
     * What type of database?
     */
    whatTypeOfDb: () => LocalizedString;
    /**
     * File path
     */
    filePath: () => LocalizedString;
    /**
     * Host
     */
    host: () => LocalizedString;
    /**
     * Port
     */
    port: () => LocalizedString;
    /**
     * Username
     */
    username: () => LocalizedString;
    /**
     * Password
     */
    password: () => LocalizedString;
    /**
     * Database name
     */
    databaseName: () => LocalizedString;
    /**
     * Connection URL
     */
    connectionUrl: () => LocalizedString;
    /**
     * ← Back to the simple form
     */
    backToSimpleForm: () => LocalizedString;
    /**
     * Have a full connection URL? Use that instead →
     */
    useFullUrl: () => LocalizedString;
    /**
     * Connect database
     */
    connectDatabaseBtn: () => LocalizedString;
    /**
     * Tip: use a view-only database account — BoloDB never writes to your data.
     */
    viewOnlyTip: () => LocalizedString;
    /**
     * Try with sample data
     */
    trySampleData: () => LocalizedString;
    /**
     * Building sample data…
     */
    buildingSample: () => LocalizedString;
    /**
     * A realistic TechStore e-commerce database, built locally for you. No setup, no credentials, ready in seconds.
     */
    sampleDataDesc: () => LocalizedString;
    /**
     * Start in seconds
     */
    startInSeconds: () => LocalizedString;
    /**
     * Couldn’t connect —
     */
    couldNotConnect: () => LocalizedString;
    /**
     * Please fill in all required fields.
     */
    fillRequired: () => LocalizedString;
    /**
     * Connection failed — check your details and try again.
     */
    connectionFailed: () => LocalizedString;
    /**
     * Reconnection failed — the database may no longer be available.
     */
    reconnectionFailed: () => LocalizedString;
    /**
     * /Users/you/data/mydb.db
     */
    dbPlaceholderSqlite: () => LocalizedString;
    /**
     * /Users/you/data/mydb.duckdb
     */
    dbPlaceholderDuckdb: () => LocalizedString;
    /**
     * localhost or db.company.com
     */
    hostPlaceholder: () => LocalizedString;
    /**
     * your_username
     */
    userPlaceholder: () => LocalizedString;
    /**
     * my_database
     */
    dbNamePlaceholder: () => LocalizedString;
    /**
     * The absolute path to your .db or .sqlite file.
     */
    sqliteFileHint: () => LocalizedString;
    /**
     * The absolute path to your DuckDB file.
     */
    duckdbFileHint: () => LocalizedString;
    /**
     * If using Docker, drop the file in the project’s data folder and use /app/data/filename.db.
     */
    dockerFileHint: () => LocalizedString;
    /**
     * Leave empty to use an in-memory database.
     */
    inMemoryDb: () => LocalizedString;
    /**
     * {n} table{n}
     */
    tablesCount: (arg: { n: unknown }) => LocalizedString;
    /**
     * just now
     */
    justNow: () => LocalizedString;
  };
  chat: {
    /**
     * view only
     */
    viewOnly: () => LocalizedString;
    /**
     * New conversation
     */
    newConversation: () => LocalizedString;
    /**
     * Ask anything about your data…
     */
    askPlaceholder: () => LocalizedString;
    /**
     * Ask a question about your data
     */
    ariaAskQuestion: () => LocalizedString;
    /**
     * Ask
     */
    askButton: () => LocalizedString;
    /**
     * Scroll to latest
     */
    scrollToLatest: () => LocalizedString;
    /**
     * {n} table{n}
     */
    tableCount: (arg: { n: unknown }) => LocalizedString;
    /**
     * Only the schema and your question are sent to Google Gemini to generate SQL — never your row data.
     */
    privacyFooter: () => LocalizedString;
    /**
     * Execute SQL query directly
     */
    sqlCommandDescription: () => LocalizedString;
    /**
     * DIRECT SQL
     */
    directSql: () => LocalizedString;
    /**
     * Direct SQL execution
     */
    directSqlReason: () => LocalizedString;
    /**
     * WHAT I UNDERSTOOD
     */
    whatIUnderstood: () => LocalizedString;
    /**
     * Generated SQL
     */
    generatedSql: () => LocalizedString;
    /**
     * View the query
     */
    viewQuery: () => LocalizedString;
    /**
     * Hide query
     */
    hideQuery: () => LocalizedString;
    /**
     * Copy
     */
    copy: () => LocalizedString;
    /**
     * ✓ Copied!
     */
    copied: () => LocalizedString;
    /**
     * ↓ Copy as CSV
     */
    copyCsv: () => LocalizedString;
    /**
     * ✓ Copied!
     */
    copiedCsv: () => LocalizedString;
    /**
     * Copy response
     */
    copyResponse: () => LocalizedString;
    /**
     * Copy prompt
     */
    copyPrompt: () => LocalizedString;
    /**
     * Edit prompt
     */
    editPrompt: () => LocalizedString;
    /**
     * Regenerate
     */
    regenerate: () => LocalizedString;
    /**
     * Yes, correct
     */
    yesCorrect: () => LocalizedString;
    /**
     * Was this the answer you were looking for?
     */
    confirmationPrompt: () => LocalizedString;
    /**
     * Verified — saved to trust history.
     */
    verifiedSaved: () => LocalizedString;
    /**
     * Based on an answer you verified before
     */
    basedOnVerified: () => LocalizedString;
    /**
     * High confidence
     */
    highConfidence: () => LocalizedString;
    /**
     * Medium confidence
     */
    mediumConfidence: () => LocalizedString;
    /**
     * Low confidence
     */
    lowConfidence: () => LocalizedString;
    /**
     * Wrong numbers
     */
    wrongNumbers: () => LocalizedString;
    /**
     * Wrong filter / dates
     */
    wrongFilter: () => LocalizedString;
    /**
     * Not what I meant
     */
    wrongIntent: () => LocalizedString;
    /**
     * Missing data
     */
    wrongMissing: () => LocalizedString;
    /**
     * Something else
     */
    wrongOther: () => LocalizedString;
    /**
     * Thought process
     */
    thoughtProcess: () => LocalizedString;
    /**
     * Schema linked
     */
    schemaLinked: () => LocalizedString;
    /**
     * Validation passed
     */
    validationPassed: () => LocalizedString;
    /**
     * Validation failed
     */
    validationFailed: () => LocalizedString;
    /**
     * Self-correction
     */
    selfCorrection: () => LocalizedString;
    /**
     * Collapse
     */
    collapse: () => LocalizedString;
    /**
     * Conversations
     */
    conversations: () => LocalizedString;
    /**
     * Clear all
     */
    clearAll: () => LocalizedString;
    /**
     * No conversations yet
     */
    noConversationsYet: () => LocalizedString;
    /**
     * Delete conversation
     */
    deleteConversation: () => LocalizedString;
    /**
     * What would you like to know?
     */
    emptyTitle: () => LocalizedString;
    /**
     * Type any question about your data in plain English. BoloDB will answer it and explain how confident it is.
     */
    emptyDescription: () => LocalizedString;
    /**
     * Questions verified for this database:
     */
    questionsVerifiedForDb: () => LocalizedString;
    /**
     * Click any question above to run it, or type your own below.
     */
    clickAnyQuestion: () => LocalizedString;
    /**
     * Not sure where to start? Try asking:
     */
    notSureWhereToStart: () => LocalizedString;
    /**
     * As you verify answers, questions specific to your data will appear here.
     */
    asYouVerify: () => LocalizedString;
    /**
     * Want better answers?
     */
    wantBetterAnswers: () => LocalizedString;
    /**
     * Create a data catalog with your business terms — add them manually or use "Suggest with AI" to auto-fill them.
     */
    catalogDescription: () => LocalizedString;
    /**
     * Power user? Type /sql SELECT ... to run SQL directly.
     */
    powerUserHint: () => LocalizedString;
    /**
     * Execution failed
     */
    executionFailed: () => LocalizedString;
    /**
     * SQL execution failed
     */
    sqlExecutionFailed: () => LocalizedString;
    /**
     * No matching commands
     */
    noMatchingCommands: () => LocalizedString;
    /**
     * No rows matched your query.
     */
    noRowsMatched: () => LocalizedString;
    /**
     * Conversation not found
     */
    conversationNotFound: () => LocalizedString;
    /**
     * Renamed successfully
     */
    renamedSuccessfully: () => LocalizedString;
    /**
     * Deleted successfully
     */
    deletedSuccessfully: () => LocalizedString;
    /**
     * Cleared successfully
     */
    clearedSuccessfully: () => LocalizedString;
    /**
     * Accuracy milestone reached
     */
    milestoneReached: () => LocalizedString;
    /**
     * Confident answers now show immediately — new questions still get a second look.
     */
    milestoneAssistedBody: () => LocalizedString;
    /**
     * Fully calibrated
     */
    fullyCalibrated: () => LocalizedString;
    /**
     * All answers appear directly now. Reasoning is always one tap away.
     */
    milestoneTrustedBody: () => LocalizedString;
    /**
     * Total: {n} quer{n}
     */
    totalQueries: (arg: { n: unknown }) => LocalizedString;
  };
  settings: {
    /**
     * Settings
     */
    title: () => LocalizedString;
    /**
     * Close settings
     */
    close: () => LocalizedString;
    /**
     * Google Gemini
     */
    googleGemini: () => LocalizedString;
    /**
     * Powers every AI feature in BoloDB
     */
    powersAi: () => LocalizedString;
    /**
     * Model
     */
    model: () => LocalizedString;
    /**
     * Not sure? Stay with "Balanced" — it works well for most databases.
     */
    modelDefaultHint: () => LocalizedString;
    /**
     * Fastest & cheapest — fine for small, simple databases
     */
    modelFast: () => LocalizedString;
    /**
     * Balanced — recommended for most uses (default)
     */
    modelBalanced: () => LocalizedString;
    /**
     * Most accurate — for large schemas and hard questions
     */
    modelAccurate: () => LocalizedString;
    /**
     * Gemini API key
     */
    apiKey: () => LocalizedString;
    /**
     * API key configured
     */
    keyConfigured: () => LocalizedString;
    /**
     * ← Cancel, keep existing key
     */
    cancelKeepKey: () => LocalizedString;
    /**
     * Get a free key at
     */
    getKeyAt: () => LocalizedString;
    /**
     * Stored locally only. Schema + question are sent to Google Gemini to generate SQL — never your table data.
     */
    keyStoredLocally: () => LocalizedString;
    /**
     * Data catalog
     */
    dataCatalog: () => LocalizedString;
    /**
     * Teach BoloDB your business terms, metrics, and value meanings so answers get more accurate.
     */
    catalogDescription: () => LocalizedString;
    /**
     * Manage data catalog →
     */
    manageCatalog: () => LocalizedString;
    /**
     * Want to connect a different database?
     */
    changeDbPrompt: () => LocalizedString;
    /**
     * Disconnect & change database
     */
    disconnectButton: () => LocalizedString;
    /**
     * Could not save settings.
     */
    couldNotSave: () => LocalizedString;
    /**
     * Could not remove key.
     */
    couldNotRemoveKey: () => LocalizedString;
  };
  dashboard: {
    /**
     * Dashboard
     */
    title: () => LocalizedString;
    /**
     * Connection
     */
    connection: () => LocalizedString;
    /**
     * Database
     */
    database: () => LocalizedString;
    /**
     * Status
     */
    status: () => LocalizedString;
    /**
     * Model
     */
    model: () => LocalizedString;
    /**
     * Confidence Distribution
     */
    confidenceDistribution: () => LocalizedString;
    /**
     * Query Activity
     */
    queryActivity: () => LocalizedString;
    /**
     * Back to Chat
     */
    backToChat: () => LocalizedString;
    /**
     * No queries yet
     */
    noQueriesYet: () => LocalizedString;
    /**
     * No activity yet
     */
    noActivityYet: () => LocalizedString;
    /**
     * This data doesn’t have a chartable format.
     */
    noChartableFormat: () => LocalizedString;
    /**
     * No table usage data
     */
    noTableUsage: () => LocalizedString;
    /**
     * No schema data
     */
    noSchemaData: () => LocalizedString;
  };
  onboard: {
    /**
     * Onboarding — BoloDB
     */
    title: () => LocalizedString;
    /**
     * Database
     */
    dbLabel: () => LocalizedString;
    /**
     * Table
     */
    tableLabel: () => LocalizedString;
    /**
     * The AI is not responding — check your API key in Settings.
     */
    aiError: () => LocalizedString;
    /**
     * You can change these settings later.
     */
    settingsTip: () => LocalizedString;
    /**
     * auto-run
     */
    autoRun: () => LocalizedString;
    /**
     * View technical details (SQL)
     */
    viewSql: () => LocalizedString;
    /**
     * Not quite
     */
    notQuite: () => LocalizedString;
    /**
     * Yes, that’s right
     */
    yesThatsRight: () => LocalizedString;
    /**
     * Getting to know your database
     */
    gettingToKnowDb: () => LocalizedString;
    /**
     * Let me look at your tables and columns so I can answer questions accurately.
     */
    profileDescription: () => LocalizedString;
    /**
     * linked
     */
    linked: () => LocalizedString;
    /**
     * Reading your database…
     */
    readingDb: () => LocalizedString;
    /**
     * Looks good — continue
     */
    looksGoodContinue: () => LocalizedString;
    /**
     * Confirm what your terms mean
     */
    confirmTerms: () => LocalizedString;
    /**
     * I found terms in your schema that might be special. Tell me what they mean so I answer correctly.
     */
    glossaryDescription: () => LocalizedString;
    /**
     * means…
     */
    means: () => LocalizedString;
    /**
     * SUGGESTED
     */
    suggested: () => LocalizedString;
    /**
     * Save terms & verify answers
     */
    saveTermsAndVerify: () => LocalizedString;
    /**
     * Check a few answers before you start
     */
    checkAnswersBeforeStart: () => LocalizedString;
    /**
     * Let me run a few automatically-generated queries so you can verify they’re right first.
     */
    startersDescription: () => LocalizedString;
    /**
     * Correct! Saved to trust history.
     */
    statusCorrect: () => LocalizedString;
    /**
     * Marked as wrong — I’ll learn from this.
     */
    statusWrong: () => LocalizedString;
    /**
     * You can always verify later from the chat.
     */
    statusSkipped: () => LocalizedString;
    /**
     * Could not generate sample queries — you can skip this step.
     */
    startersError: () => LocalizedString;
    /**
     * Start asking →
     */
    startAsking: () => LocalizedString;
    /**
     * Review each answer above to continue.
     */
    reviewEachAnswer: () => LocalizedString;
    /**
     * Read your DB
     */
    stepReadDb: () => LocalizedString;
    /**
     * Define terms
     */
    stepDefineTerms: () => LocalizedString;
    /**
     * Check answers
     */
    stepCheckAnswers: () => LocalizedString;
  };
  schema: {
    /**
     * Schema
     */
    title: () => LocalizedString;
    /**
     * Every answer waits for your confirmation while it learns.
     */
    trustSupervised: () => LocalizedString;
    /**
     * Confident answers are shown; novel ones get a second look.
     */
    trustAssisted: () => LocalizedString;
    /**
     * Answers are shown directly. Reasoning is one tap away.
     */
    trustTrusted: () => LocalizedString;
    /**
     * Supervised
     */
    supervised: () => LocalizedString;
    /**
     * Assisted
     */
    assisted: () => LocalizedString;
    /**
     * Trusted
     */
    trusted: () => LocalizedString;
    /**
     * Synonyms
     */
    synonyms: () => LocalizedString;
    /**
     * Value meanings
     */
    valueMeanings: () => LocalizedString;
    /**
     * Metrics
     */
    metrics: () => LocalizedString;
    /**
     * Join paths
     */
    joinPaths: () => LocalizedString;
    /**
     * Column notes
     */
    columnNotes: () => LocalizedString;
    /**
     * Suggest with AI
     */
    suggestWithAi: () => LocalizedString;
    /**
     * Save catalog
     */
    saveCatalog: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
  };
  errors: {
    /**
     * The database server isn’t running or can’t be reached — check the host and port.
     */
    dbConnectionRefused: () => LocalizedString;
    /**
     * Wrong username or password — double-check your credentials.
     */
    wrongCredentials: () => LocalizedString;
    /**
     * File not found — check the path and make sure the file exists.
     */
    fileNotFound: () => LocalizedString;
    /**
     * That database name wasn’t found — check the spelling.
     */
    dbDoesNotExist: () => LocalizedString;
    /**
     * Connection timed out — the server may be unreachable or behind a firewall.
     */
    connectionTimedOut: () => LocalizedString;
    /**
     * SSL error — if connecting via URL mode, try adding ?sslmode=disable at the end.
     */
    sslError: () => LocalizedString;
    /**
     * The driver for that database type isn’t installed on this server.
     */
    driverNotInstalled: () => LocalizedString;
    /**
     * Access Denied
     */
    accessDenied: () => LocalizedString;
    /**
     * Session Expired, please login again
     */
    sessionExpired: () => LocalizedString;
    /**
     * Invalid Token
     */
    invalidToken: () => LocalizedString;
    /**
     * Invalid credentials
     */
    invalidCredentials: () => LocalizedString;
    /**
     * Email already Registered
     */
    emailAlreadyRegistered: () => LocalizedString;
    /**
     * Invalid Google token
     */
    invalidGoogleToken: () => LocalizedString;
    /**
     * Google account has no email
     */
    googleNoEmail: () => LocalizedString;
    /**
     * Google email is not verified
     */
    googleEmailNotVerified: () => LocalizedString;
    /**
     * User not found
     */
    userNotFound: () => LocalizedString;
    /**
     * Incorrect Password, Please try again
     */
    incorrectPassword: () => LocalizedString;
    /**
     * An internal error has occurred.
     */
    internalError: () => LocalizedString;
    /**
     * No database connected
     */
    noDatabaseConnected: () => LocalizedString;
    /**
     * Empty question
     */
    emptyQuestion: () => LocalizedString;
    /**
     * Could not form a query — try rephrasing
     */
    couldNotFormQuery: () => LocalizedString;
    /**
     * Could not form a working query — try rephrasing
     */
    couldNotFormWorkingQuery: () => LocalizedString;
    /**
     * SQL generation exceeded maximum time limit
     */
    sqlGenerationTimeout: () => LocalizedString;
    /**
     * Query generation failed
     */
    queryGenerationFailed: () => LocalizedString;
    /**
     * Model returned empty SQL
     */
    modelReturnedEmptySql: () => LocalizedString;
    /**
     * Retrying with corrections
     */
    retryingCorrections: () => LocalizedString;
    /**
     * The query could not be run against the database.
     */
    queryCouldNotRun: () => LocalizedString;
    /**
     * Could not generate valid SQL after {n} attempts
     */
    couldNotGenerateValidSql: (arg: { n: unknown }) => LocalizedString;
    /**
     * No Database Connected
     */
    noDatabaseConnectedShort: () => LocalizedString;
    /**
     * Empty statement.
     */
    emptyStatement: () => LocalizedString;
    /**
     * Only SELECT queries are allowed (read-only mode).
     */
    selectOnly: () => LocalizedString;
    /**
     * Only one statement is allowed (no stacked queries).
     */
    singleStatementOnly: () => LocalizedString;
    /**
     * SELECT INTO is not allowed.
     */
    selectIntoNotAllowed: () => LocalizedString;
    /**
     * The AI API key appears to be invalid or expired.
     */
    aiKeyInvalid: () => LocalizedString;
    /**
     * The AI service denied access — check your API key.
     */
    aiKeyDenied: () => LocalizedString;
    /**
     * The requested AI model was not found.
     */
    aiModelNotFound: () => LocalizedString;
    /**
     * The AI service returned an unexpected error.
     */
    aiUnexpectedError: () => LocalizedString;
    /**
     * The AI declined to answer this question.
     */
    aiDeclined: () => LocalizedString;
    /**
     * The AI returned an empty answer — please try again.
     */
    aiEmptyAnswer: () => LocalizedString;
    /**
     * LLM error: {error}
     */
    llmError: (arg: { error: unknown }) => LocalizedString;
    /**
     * Entry not found or unauthorized
     */
    entryNotFound: () => LocalizedString;
    /**
     * the generated query did not run
     */
    reasonQueryDidNotRun: () => LocalizedString;
    /**
     * closely matches an answer you verified before
     */
    reasonMatchesVerified: () => LocalizedString;
    /**
     * similar to an answer you verified before
     */
    reasonSimilarToVerified: () => LocalizedString;
    /**
     * no matching rows
     */
    reasonNoMatchingRows: () => LocalizedString;
    /**
     * new question — please confirm it is right
     */
    reasonNewQuestion: () => LocalizedString;
  };
  streaming: {
    /**
     * Scanning tables: {tables}
     */
    scanningTables: (arg: { tables: unknown }) => LocalizedString;
    /**
     * Translating business term: '{term}'
     */
    translatingTerm: (arg: { term: unknown }) => LocalizedString;
    /**
     * Generating SQL…
     */
    generatingSql: () => LocalizedString;
    /**
     * Running query…
     */
    runningQuery: () => LocalizedString;
    /**
     * Validating…
     */
    validating: () => LocalizedString;
  };
  chart: {
    /**
     * Chart
     */
    chart: () => LocalizedString;
    /**
     * Table
     */
    table: () => LocalizedString;
  };
};

export type Formatters = {};
